ood_dataset:
  name: cifar10_ood
  num_classes: 10

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  dataset_class: ImglistDataset

  batch_size: 128
  shuffle: False

  # split_names: [val, nearood, farood, t_out, d_out]
  split_names: [val, nearood, farood]
  val:
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/cifar10/val_tin.txt
  nearood:
    datasets: [tin, cifar100]
    tin:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar10/test_tin.txt
    cifar100:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar10/test_cifar100.txt
  farood:
    datasets: [mnist, svhn, texture, place365]
    mnist:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar10/test_mnist.txt
    svhn:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar10/test_svhn.txt
    texture:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar10/test_texture.txt
    place365:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar10/test_places365.txt
  # t_out:
  #   datasets: [tin, cifar100,mnist, svhn, texture, places365]
  #   tin:
  #     data_dir: ./data/images_classic/
  #     imglist_pth: ./data/benchmark_imglist/my_cifar10/val_tin.txt
  #   cifar100:
  #     data_dir: ./data/images_classic/
  #     imglist_pth: ./data/benchmark_imglist/my_cifar10/val_cifar100.txt
  #   mnist:
  #     data_dir: ./data/images_classic/
  #     imglist_pth: ./data/benchmark_imglist/my_cifar10/val_mnist.txt
  #   svhn:
  #     data_dir: ./data/images_classic/
  #     imglist_pth: ./data/benchmark_imglist/my_cifar10/val_svhn.txt
  #   texture:
  #     data_dir: ./data/images_classic/
  #     imglist_pth: ./data/benchmark_imglist/my_cifar10/val_texture.txt
  #   places365:
  #     data_dir: ./data/images_classic/
  #     imglist_pth: ./data/benchmark_imglist/my_cifar10/val_places365.txt
  # d_out:
  #   datasets: [oe]
  #   oe:
  #     data_dir: ./data/images_classic/
  #     imglist_pth: ./data/benchmark_imglist/cifar10/train_tin597.txt